// import { UserRoleEnum } from "../enums/user.enum";

// const roleSpecificFields: Partial<Record<UserRoleEnum, (keyof any)[]>> = {
//   TALENT: [
//     'skills',
//     'referralCode',
//     'totalReferrals',
//     'socials',
//     'profilePhoto',
//     'visibility',
//     'email',
//     'phone',
//     'role',
//     'authSource',
//     'profileCompleted',
//     'emailVerified',
//     'termsAndConditionsAccepted',
//     'lastLoginAt',
//     '_id',
//     'createdAt',
//     'updatedAt',
//   ],
//   ORGANIZATION: [
//     'totalJobPost',
//     'talentContacted',
//     'activePost',
//     'activeConversations',
//     'responseRate',
//     'successfulHire',
//     'visibility',
//     'email',
//     'phone',
//     'role',
//     'authSource',
//     'profileCompleted',
//     'emailVerified',
//     'termsAndConditionsAccepted',
//     'lastLoginAt',
//     '_id',
//     'createdAt',
//     'updatedAt',
//   ],
// };
