export enum CredentialTypeEnum {
  DEGREE = 'DEGREE',
  CERTIFICATE = 'CERTIFICATE',
  LICENSE = 'LICENSE',
  AWARD = 'AWARD',
  TRAINING = 'TRAINING',
  WORK_EXPERIENCE = 'WORK_EXPERIENCE',
  PROJECT_PORTFOLIO = 'PROJECT_PORTFOLIO',
  RECOMMENDATION_LETTER = 'RECOMMENDATION_LETTER',
  OTHER = 'OTHER',
}

export enum CredentialCategoryEnum {
  EDUCATION = 'EDUCATION',
  PROFESSIONAL = 'PROFESSIONAL',
  LICENSE = 'LICENSE',
  TECHNICAL_SKILLS = 'TECHNICAL_SKILLS',
  LANGUAGE = 'LANGUAGE',
  INDUSTRY_SPECIFIC = 'INDUSTRY_SPECIFIC',
  LEADERSHIP = 'LEADERSHIP',
  PROJECT_MANAGEMENT = 'PROJECT_MANAGEMENT',
  OTHER = 'OTHER',
}

export enum CredentialStatusEnum {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum VerificationLevelEnum {
  LOW = 'LOW',
  MID = 'MID',
  HIGH = 'HIGH',
}
