export enum WaitlistInterestEnum {
  TALENT = 'TALENT',
  ORGANIZATION = 'ORGANIZATION',
  INVESTOR = 'INVESTOR',
  VOLUNTEER = 'VOLUNTEER',
  BETA_TESTER = 'BETA_TESTER',
  AMBASSADOR = 'AMBASSADOR',
}
